test on wc

diff --git a/.github/workflows/conformance_weight_compression.yml b/.github/workflows/conformance_weight_compression.yml
--- a/.github/workflows/conformance_weight_compression.yml
+++ b/.github/workflows/conformance_weight_compression.yml
@@ -36,8 +36,70 @@ env:
   HOME_HF: "/home/runner/hf_home"
 
 jobs:
-  weight-compression-cpu:
-    name: Weight compression [${{ matrix.group }}/6]
+  # weight-compression-cpu:
+  #   name: Weight compression [${{ matrix.group }}/6]
+  #   runs-on: ubuntu-latest-16-cores
+  #   timeout-minutes: 60
+  #   strategy:
+  #     fail-fast: false
+  #     matrix:
+  #       group: [1, 2, 3, 4, 5, 6]
+  #   steps:
+  #     - name: CPU Info
+  #       run: awk 'BEGIN{RS=""} END{print}' /proc/cpuinfo
+  #     - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
+  #       with:
+  #         ref: ${{ inputs.pr_num != '' && format('refs/pull/{0}/head', inputs.pr_num) || github.ref }}
+
+  #     - uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7.0.0
+  #       with:
+  #         python-version: ${{ env.PYTHON_VERSION }}
+  #     - name: Install uv
+  #       uses: astral-sh/setup-uv@c18668ad3cf93ea998bef934396af7bb5c839dc7 # v10.2.0
+  #     - name: Install NNCF and test requirements
+  #       run: uv pip install --system . -r tests/post_training/requirements.txt
+  #     - name: Print installed modules
+  #       run: pip list
+  #     - name: Run wc test scope
+  #       run: |
+  #         set +e
+  #         python -m pytest -s -ra tests/post_training/test_quantize_conformance.py::test_weight_compression \
+  #           --junit-xml=${{ env.RESULT_XML }} \
+  #           --durations-path=tests/post_training/data/wc_test_durations.json \
+  #           --splitting-algorithm=least_duration \
+  #           --splits 6 \
+  #           --group ${{ matrix.group }} \
+  #           ${{ env.PYTEST_ARGS }}
+  #         ret=$?
+  #         [ $ret -eq 5 ] && [ -n "${{ env.PYTEST_ARGS }}" ]  && exit 0 || exit $ret
+  #     - name: Print results.csv
+  #       if: ${{ !cancelled() }}
+  #       run: column -s, -t < tmp/results.csv || echo "no file"
+  #     - name: Upload artifact
+  #       if: ${{ !cancelled() }}
+  #       uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a #v7.0.1
+  #       with:
+  #         name: wc_results_${{ matrix.group }}
+  #         path: tmp/results.csv
+  #         if-no-files-found: ignore
+  #     - name: Upload test results
+  #       if: ${{ !cancelled() }}
+  #       uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
+  #       with:
+  #         name: weight-compression-pytest-results-${{ matrix.group }}
+  #         path: ${{ env.RESULT_XML }}
+  #         retention-days: 7
+
+  # summary:
+  #   name: Summary WC
+  #   if: ${{ !cancelled() }}
+  #   needs: weight-compression-cpu
+  #   uses: ./.github/workflows/call_summary.yml
+  #   with:
+  #     artifact_pattern: weight-compression-pytest-results-*
+
+  ptq-quantization-cpu:
+    name: PTQ quantization [${{ matrix.group }}/6]
     runs-on: ubuntu-latest-16-cores
     timeout-minutes: 60
     strategy:
@@ -60,12 +122,12 @@ jobs:
         run: uv pip install --system . -r tests/post_training/requirements.txt
       - name: Print installed modules
         run: pip list
-      - name: Run wc test scope
+      - name: Run PTQ test scope
         run: |
           set +e
-          python -m pytest -s -ra tests/post_training/test_quantize_conformance.py::test_weight_compression \
+          python -m pytest -s -ra tests/post_training/test_quantize_conformance.py::test_ptq_quantization \
             --junit-xml=${{ env.RESULT_XML }} \
-            --durations-path=tests/post_training/data/wc_test_durations.json \
+            --durations-path=tests/post_training/data/ptq_test_durations.json \
             --splitting-algorithm=least_duration \
             --splits 6 \
             --group ${{ matrix.group }} \
@@ -79,21 +141,21 @@ jobs:
         if: ${{ !cancelled() }}
         uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a #v7.0.1
         with:
-          name: wc_results_${{ matrix.group }}
+          name: ptq_results_${{ matrix.group }}
           path: tmp/results.csv
           if-no-files-found: ignore
       - name: Upload test results
         if: ${{ !cancelled() }}
         uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
         with:
-          name: weight-compression-pytest-results-${{ matrix.group }}
+          name: ptq-quantization-pytest-results-${{ matrix.group }}
           path: ${{ env.RESULT_XML }}
           retention-days: 7
 
   summary:
-    name: Summary WC
+    name: Summary PTQ
     if: ${{ !cancelled() }}
-    needs: weight-compression-cpu
+    needs: ptq-quantization-cpu
     uses: ./.github/workflows/call_summary.yml
     with:
-      artifact_pattern: weight-compression-pytest-results-*
+      artifact_pattern: ptq-quantization-pytest-results-*
