skip

diff --git a/.github/workflows/examples.yml b/.github/workflows/examples.yml
--- a/.github/workflows/examples.yml
+++ b/.github/workflows/examples.yml
@@ -50,48 +50,48 @@ env:
   PYTHON_VERSION: "3.12"
 
 jobs:
-  examples-cpu:
-    name: Test examples CPU [${{ matrix.group }}/6]
-    runs-on: ubuntu-latest-16-cores
-    timeout-minutes: 80
-    strategy:
-      fail-fast: false
-      matrix:
-        group: [1, 2, 3, 4, 5, 6]
-    steps:
-      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
-        with:
-          ref: ${{ inputs.pr_num != '' && format('refs/pull/{0}/head', inputs.pr_num) || github.ref }}
-      - uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7.0.0
-        with:
-          python-version: ${{ env.PYTHON_VERSION }}
-      - name: cpuinfo
-        run: cat /proc/cpuinfo
-      - name: Install test requirements
-        run: |
-          pip install -r tests/cross_fw/examples/requirements.txt
-      - name: Print installed modules
-        run: pip list
-      - name: Run examples test scope
-        run: |
-          set +e
-          python -m pytest -s -ra tests/cross_fw/examples \
-            -m 'not cuda' \
-            --junit-xml=${{ env.RESULT_XML }} \
-            --durations-path=tests/cross_fw/examples/test_durations.json \
-            --splitting-algorithm=least_duration \
-            --splits 6 \
-            --group ${{ matrix.group }} \
-            ${{ env.PYTEST_ARGS }}
-          ret=$?
-          [ $ret -eq 5 ] && [ -n "${{ inputs.pytest_args || '' }}" ]  && exit 0 || exit $ret
-      - name: Upload test results
-        if: ${{ !cancelled() }}
-        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
-        with:
-          name: examples-cpu-pytest-results-${{ matrix.group }}
-          path: ${{ env.RESULT_XML }}
-          retention-days: 7
+  # examples-cpu:
+  #   name: Test examples CPU [${{ matrix.group }}/6]
+  #   runs-on: ubuntu-latest-16-cores
+  #   timeout-minutes: 80
+  #   strategy:
+  #     fail-fast: false
+  #     matrix:
+  #       group: [1, 2, 3, 4, 5, 6]
+  #   steps:
+  #     - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
+  #       with:
+  #         ref: ${{ inputs.pr_num != '' && format('refs/pull/{0}/head', inputs.pr_num) || github.ref }}
+  #     - uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7.0.0
+  #       with:
+  #         python-version: ${{ env.PYTHON_VERSION }}
+  #     - name: cpuinfo
+  #       run: cat /proc/cpuinfo
+  #     - name: Install test requirements
+  #       run: |
+  #         pip install -r tests/cross_fw/examples/requirements.txt
+  #     - name: Print installed modules
+  #       run: pip list
+  #     - name: Run examples test scope
+  #       run: |
+  #         set +e
+  #         python -m pytest -s -ra tests/cross_fw/examples \
+  #           -m 'not cuda' \
+  #           --junit-xml=${{ env.RESULT_XML }} \
+  #           --durations-path=tests/cross_fw/examples/test_durations.json \
+  #           --splitting-algorithm=least_duration \
+  #           --splits 6 \
+  #           --group ${{ matrix.group }} \
+  #           ${{ env.PYTEST_ARGS }}
+  #         ret=$?
+  #         [ $ret -eq 5 ] && [ -n "${{ inputs.pytest_args || '' }}" ]  && exit 0 || exit $ret
+  #     - name: Upload test results
+  #       if: ${{ !cancelled() }}
+  #       uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
+  #       with:
+  #         name: examples-cpu-pytest-results-${{ matrix.group }}
+  #         path: ${{ env.RESULT_XML }}
+  #         retention-days: 7
 
   build_cuda_docker:
     if: ${{ !inputs.skip_gpu }}
@@ -176,67 +176,67 @@ jobs:
           path: ${{ env.RESULT_XML }}
           retention-days: 7
 
-  examples-win-cpu:
-    name: Test examples CPU Windows [${{ matrix.group }}/6]
-    runs-on: windows-2025-16-core
-    timeout-minutes: 80
-    if: ${{ !inputs.skip_windows }}
-    strategy:
-      fail-fast: false
-      matrix:
-        group: [1, 2, 3, 4, 5, 6]
-    env:
-      PYTHONIOENCODING: utf-8
-      NNCF_EXTENSION_LOAD_TIMEOUT: 180
-    steps:
-      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
-        with:
-          ref: ${{ inputs.pr_num != '' && format('refs/pull/{0}/head', inputs.pr_num) || github.ref }}
-      - uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7.0.0
-        with:
-          python-version: ${{ env.PYTHON_VERSION }}
-      - uses: ilammy/msvc-dev-cmd@0b201ec74fa43914dc39ae48a89fd1d8cb592756 # v1.13.0
-      - name: Install NNCF and test requirements
-        run: |
-          pip install -r tests/cross_fw/examples/requirements.txt
-      - name: Print installed modules
-        run: pip list
-      - name: Run examples test scope
-        run: |
-          set +e
+  # examples-win-cpu:
+  #   name: Test examples CPU Windows [${{ matrix.group }}/6]
+  #   runs-on: windows-2025-16-core
+  #   timeout-minutes: 80
+  #   if: ${{ !inputs.skip_windows }}
+  #   strategy:
+  #     fail-fast: false
+  #     matrix:
+  #       group: [1, 2, 3, 4, 5, 6]
+  #   env:
+  #     PYTHONIOENCODING: utf-8
+  #     NNCF_EXTENSION_LOAD_TIMEOUT: 180
+  #   steps:
+  #     - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
+  #       with:
+  #         ref: ${{ inputs.pr_num != '' && format('refs/pull/{0}/head', inputs.pr_num) || github.ref }}
+  #     - uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7.0.0
+  #       with:
+  #         python-version: ${{ env.PYTHON_VERSION }}
+  #     - uses: ilammy/msvc-dev-cmd@0b201ec74fa43914dc39ae48a89fd1d8cb592756 # v1.13.0
+  #     - name: Install NNCF and test requirements
+  #       run: |
+  #         pip install -r tests/cross_fw/examples/requirements.txt
+  #     - name: Print installed modules
+  #       run: pip list
+  #     - name: Run examples test scope
+  #       run: |
+  #         set +e
 
-          sys_lib="$(python -c "import sysconfig; print(sysconfig.get_config_var('LIBDIR'))")"
-          prefix_lib="$(python -c "import sys; print(sys.prefix + '/libs')")"
-          include_dir="$(python -c "import sysconfig; print(sysconfig.get_path('include'))")"
+  #         sys_lib="$(python -c "import sysconfig; print(sysconfig.get_config_var('LIBDIR'))")"
+  #         prefix_lib="$(python -c "import sys; print(sys.prefix + '/libs')")"
+  #         include_dir="$(python -c "import sysconfig; print(sysconfig.get_path('include'))")"
 
-          export LIB="${LIB};${sys_lib};${prefix_lib}"
-          export INCLUDE="${INCLUDE};${include_dir}"
+  #         export LIB="${LIB};${sys_lib};${prefix_lib}"
+  #         export INCLUDE="${INCLUDE};${include_dir}"
 
-          python -m pytest -s -ra tests/cross_fw/examples \
-            -m 'not cuda' \
-            --junit-xml=${{ env.RESULT_XML }} \
-            --durations-path=tests/cross_fw/examples/test_durations.json \
-            --splitting-algorithm=least_duration \
-            --splits 6 \
-            --group ${{ matrix.group }} \
-            ${{ env.PYTEST_ARGS }}
-          ret=$?
-          [ $ret -eq 5 ] && [ -n "${{ inputs.pytest_args || '' }}" ]  && exit 0 || exit $ret
-      - name: Upload test results
-        if: ${{ !cancelled() }}
-        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
-        with:
-          name: examples-win-cpu-pytest-results-${{ matrix.group }}
-          path: ${{ env.RESULT_XML }}
-          retention-days: 7
+  #         python -m pytest -s -ra tests/cross_fw/examples \
+  #           -m 'not cuda' \
+  #           --junit-xml=${{ env.RESULT_XML }} \
+  #           --durations-path=tests/cross_fw/examples/test_durations.json \
+  #           --splitting-algorithm=least_duration \
+  #           --splits 6 \
+  #           --group ${{ matrix.group }} \
+  #           ${{ env.PYTEST_ARGS }}
+  #         ret=$?
+  #         [ $ret -eq 5 ] && [ -n "${{ inputs.pytest_args || '' }}" ]  && exit 0 || exit $ret
+  #     - name: Upload test results
+  #       if: ${{ !cancelled() }}
+  #       uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
+  #       with:
+  #         name: examples-win-cpu-pytest-results-${{ matrix.group }}
+  #         path: ${{ env.RESULT_XML }}
+  #         retention-days: 7
 
-  examples-cpu-summary:
-    name: Summary Examples CPU
-    if: ${{ !cancelled() }}
-    needs: examples-cpu
-    uses: ./.github/workflows/call_summary.yml
-    with:
-      artifact_pattern: examples-cpu-pytest-results-*
+  # examples-cpu-summary:
+  #   name: Summary Examples CPU
+  #   if: ${{ !cancelled() }}
+  #   needs: examples-cpu
+  #   uses: ./.github/workflows/call_summary.yml
+  #   with:
+  #     artifact_pattern: examples-cpu-pytest-results-*
 
   examples-cuda-summary:
     name: Summary Examples CUDA
@@ -246,10 +246,10 @@ jobs:
     with:
       artifact_pattern: examples-cuda-pytest-results-*
 
-  examples-win-cpu-summary:
-    name: Summary Examples Windows CPU
-    if: ${{ !cancelled() && !inputs.skip_windows }}
-    needs: examples-win-cpu
-    uses: ./.github/workflows/call_summary.yml
-    with:
-      artifact_pattern: examples-win-cpu-pytest-results-*
+  # examples-win-cpu-summary:
+  #   name: Summary Examples Windows CPU
+  #   if: ${{ !cancelled() && !inputs.skip_windows }}
+  #   needs: examples-win-cpu
+  #   uses: ./.github/workflows/call_summary.yml
+  #   with:
+  #     artifact_pattern: examples-win-cpu-pytest-results-*
